### ISSUE TITLE
Understanding spatial loops

### ISSUE THREAD

**Issue by suyashbakshi** [ZigZag-Project/zigzag-v1#13]
Hi,
I'm having some trouble understanding the meaning of spatial loops in Zigzag.

As I understand, spatial loops are supposed to be the innermost level in the mapping. And in a simplistic case 1 iteration of spatial loops gets executed by 1 PE. And each time the spatial unrolling is executed on PEs, each PE reads 1 element each of output, weight and input from their register file and stores back the computed output element, right?

And if above is true, why does it say in the paper (under Fig.3.):
"yet, there is no need for spatial loops of individual operands to follow the same order or appear at the same level"
I understand that loop order at spatial level does not matter, but what's the need to worry about "level" of the spatial loops when they are already supposed to be the innermost loop?

If my understanding is incorrect, could you help me understand the relevance of "level" for the spatial mapping? And more specifically, it would be very helpful if you could comment on spatial mapping being on different levels for operands in the mapping in Fig.3.(b) of the paper please?

**Comment by LY-Mei** [comment]
Hi Firebird,

Thank you for the question! It's a good question.

In Fig.3 of the paper, the spatial unrollings of all 4 cases (a/b/c/d) are actually the same: W/I/O have spatially unrolled the same loop factors at their innermost memory level (Reg File). It indicates that there is the same number of W/I/O-RegFile units actively used in those corresponding mapping scenarios. 

There are other HW configurations and spatial mapping possibilities in real designs. Current ZigZag data representation allocates spatial unrolling loops to different architectural levels for different operands to capture all the possibilities.

Let me give you an example to illustrate this.
![image](https://user-images.githubusercontent.com/55059827/148884835-07c050c7-02bc-419f-bddc-4e6b3890a9b4.png)

In the above figure, there is a MAC array of 4x3 with spatial mapping of "Ku 4 | OXu 3". To capture the uneven spatial unrolling scheme of W/I/O-RegFile (i.e., there are 4 W-Reg, 3 I-Reg, and 12 O-Reg), the spatial loops are allocated differently for each operand across levels. ZigZag uses the simplified version for spatial mapping representation, as in the 2nd table, in which the repetitive loop terms in the lower architectural level are canceled out if the same terms also show up in the upper level.

Hope I have answered your question. Let me know if you have any further doubt!

Best regards,
Linyan

**Comment by suyashbakshi** [comment]
Thank you for the quick response, but I'm even more confused now.

1. My understanding was that each PE/MAC-unit had its own private register file. I assumed this from the "memory_unroll" factor for register file memory in the "architecture.yaml" file, which I thought defined the number of unique instances of that memory unit. But, this doesn't appear from the example you're showing. So what does the "memory_unroll" parameter mean?

2. I think you missed to answer this, but 1 spatial unrolling loop iteration is executed on 1 PE right? So in the example you show, there are Ku*OXu = 12 spatially unrolled iterations, right? Meaning that, MAC unit on top-left corner will use the data elements of each operand corresponding to indexes (OXu=0, Ku=0), the MAC unit to its right will use (OXu=0, Ku=1) and so on, right?

3. What's the difference between assigning spatial loops to MAC-level and Reg-file level? Because reg-file level already has temporal loops assigned to it. So, Is it just a matter of representation? One observation I could make was that: spatial loop in reg-file level describe the unique instances of register files needed for that operand, and spatial loop in MAC level describe the reuse by the MAC-units.

**Comment by LY-Mei** [comment]
1. Each PE/MAC-unit can have or not have its own private register file for each operand W/I/O in ZigZag. In the default architecture setting file we provided, each PE/MAC-unit does have a register file for each operand indeed. You understand the "memory_unroll" correctly. For the case that each MAC has all W/I/O 3 register files, the simplified spatial unrolling for the above example becomes:
![image](https://user-images.githubusercontent.com/55059827/149053975-295621d8-501e-4d7d-ade1-579ceae4fe4f.png)

2. Yes, you are fully correct! 1 spatial unrolling loop iteration is executed on 1 PE if we assume the PE only contains 1 MAC unit, and here we have Ku*OXu = 12 spatially unrolled iterations which can happen in parallel. Each PE uses its the data corresponding to its "geographic" index.

3. We use spatial mapping (spatial loop) to discribe each architectural level's unrolling count, starting from the innermost MAC level to the outermost memory level (e.g., DRAM). There are two more examples. Hope can help you understand better.
![image](https://user-images.githubusercontent.com/55059827/149056332-a2963f4c-41a0-4fb6-b65d-16d96516451d.png)
![image](https://user-images.githubusercontent.com/55059827/149057035-09b78b29-c251-41e4-b335-61b7c29a0c96.png)

One important thing to keep in mind is that when you see the spatial mapping in ZigZag, you always see the simplied version as I mentioned in the previous answer: **the repetitive loop terms in the lower architectural level are canceled out if the same terms also show up in the upper level**. So, you can understand that each architectural level sees the spatial loops assigned to it and also sees the spatial loops at all above levels. It's just that we don't explicitly write it out. 

The reason we do that is on one hand to simplify the mapping representation format (like shown in the below figure, you see how cumbersome and repetative the reporesentation becomes if we don't simplify it, right).

![image](https://user-images.githubusercontent.com/55059827/149059053-d34ba7e5-ae88-4239-8d27-a8e0788a31d5.png)

On the other hand, we do it to unify with the temporal mapping representation. Even without noticing it, we have already by default accepted that for temporal mapping, each memory level sees the temporal loops assign to it and also sees the temporal loops at all **below** levels, e.g., the top DRAM level will see all the temporal loops and know that the number of cycle it need to iterate through is the total temporal loops' product. For spatial mapping, it's the opposite, each architectural level sees the spatial loops assign to it and also sees the spatial loops at all **above** levels, e.g., the bottom MAC level will see all the spatial loops and know that the active number of unit it need to use is the total spatial loops' product.

I hope I have made things more clear now! Let me know if you have further questions!

**Comment by suyashbakshi** [comment]
Thank you so much! Its a lot more clear now. Just a few more follow-up questions if you don't mind.

1. If a spatial unrolling factor is assigned to a memory level, then does that override the "memory_unroll" parameter? Or am I mixing up two different concepts?

2. For this example:
![image](https://user-images.githubusercontent.com/16914056/149160996-eaf583dc-8966-4438-9e3a-9c8550796d90.png)
Maybe this one does not make sense, but let's assume that there was a register file for weights **which was assigned some temporal loops**, but no spatial unrolling factor was assigned to it. Something like:
MAC-level: [OXu,3], Reg-level: [empty], LB-level: [Ku,4]
Then does that mean there would have been only 1 register file shared by all MAC units? 

3. This is probably straightforward but I'd rather confirm it. Assume that we assigned spatial unrolling factor 'Ku' to a memory level, say LB level. Does that mean the temporal loop (if any) 'K' at LB level is now a "parallel-for" ?

Thank you for your patience with all these questions.

**Comment by LY-Mei** [comment]
1. Yes, you are right! If users define the spatial mapping by themselves, indeed it will overwrite the "memory_unroll" parameter. The "memory_unroll" parameter is used to guide the spatial mapping search engine. If we don't search for spatial mapping, but manually define it, then the "memory_unroll" parameter doesn't matter.

2. In that case, the spatial mapping will become：
![image](https://user-images.githubusercontent.com/55059827/149266860-2ccb2bd9-2972-4afc-aa27-07cbdedad70d.png)
Since we always assume the below arch level can see all the spatial unrolling loops of levels above, it guarantees that the below arch level will always have a larger/equal number of unrolling units than/as the unrolling unit count of the levels above, i.e., active MAC count >= active Reg count >= active LB count in all those examples.

3. No, the temporal loops are not impacted by the spatial loops that we assigned to each level. If there is a "K" temporal loop at LB level, whether or not that level has a "Ku" spatial loop, the "K" temporal loop will be there, unless the actual memory capacity of any memory level in the system is not respected (allocated data size> memory capacity), then the mapping becomes an invalid one. But that's a different story.

You are welcome, Firebird! We are always happy to help. :)

**Comment by suyashbakshi** [comment]
Thank you for answering all the questions. That's all I had for now. Closing the issue.
