### ISSUE TITLE
Combination generator a possible bottleneck?

### ISSUE THREAD

**Issue by suyashbakshi** [ZigZag-Project/zigzag-v1#15]
Hello, I have a question about the cases when there are high number of LPFs for a layer. For example, I defined a layer with dimensions:
K = 256, C = 512, OY=OX=64, FY=FX=3 (total LPFs = 31)

When I run the framework, I get the following message:
```
python3 top_module.py --arch ./inputs/architecture.yaml --map ./inputs/mapping.yaml --set ./inputs/settings.yaml --mempool ./inputs/memory_pool.yaml

ZigZag started running.
Target workload: DenseNet121 | Layer(s): [132]
MEM HIERARCHY  1 / 1
memory size: {'W': [3584, 884736, 2516582400], 'I': [3584, 884736, 2516582400], 'O': [3584, 884736, 2516582400]}
memory unroll: {'W': [256, 1, 1], 'I': [256, 1, 1], 'O': [256, 1, 1]}
memory share: {0: [('W', 2), ('I', 2), ('O', 2)], 1: [('W', 1), ('I', 1), ('O', 1)]}
15:40:42 DenseNet121 L 132 , M 1 / 1  SUG started
```

And the execution waits for several 10's of minutes at this stage. It appears to me that the subroutine that generates all the combinations of LPFs is the bottleneck behind this. 

As I understand, the settings param "max_nb_lpf_layer" is only useful once the "valid" combinations have been identified. However, in the case above, the subroutine appears to be stuck in generating all possible combinations.

Is there a way to overcome this issue?

Thank you
Suyash

**Comment by asyms** [comment]
Hi Suyash,

Thanks for the question. 

The `max_nb_lpf_layer` setting only influences the max number of LPFs used for the LOMA engine (which is a temporal mapping engine, and thus comes after the spatial unrolling generation).

Which spatial unrolling search engine are you using here? The execution time required for the spatial unrolling generation depends heavily on the engine chosen.

Regards,
Arne

**Comment by suyashbakshi** [comment]
I used heuristic_v2 as the search method with a spatial utilization threshold of 0.85

**Comment by asyms** [comment]
You probably noticed that setting the minimal spatial utilization to a larger threshold value of 0.9 or 0.95 results in a faster SUG. But if you really require a threshold of 0.85, I'm afraid that is the execution cost of the `heuristic_v2` search.

I suggest you to try out the `hint_driven` search method, this requires setting a list of loop types you want zigzag to try for the PE array dimensions. This does however require you have some coarse idea of what spatial unrolling you would want to try.

**Comment by suyashbakshi** [comment]
Thank you. Yes, apparently for the hardware architecture that I'm playing around with, setting a higher spatial utilization results in no spatial unrolling being found.

From a little more fooling around in the code, it appears that the loop at line:1544 in msg.py is the bottleneck. Because for the layer I described above, there are 31 LPFs. And the function "combinations()" has to naively generate the combinations of length 1 to 31. It worked fine up till length 4 combinations for me, after that it is stuck, and rightly so, since the total combinations at length 5 are ~170k, and reaching upto 300M for combinations of length 15.

The hint driven method looks interesting, I will try that. However, I was rather interested in letting the tool explore a larger search space for other analysis.

Thank you for your quick response.
