### ISSUE TITLE
Question about memory capacity and mapping

### ISSUE THREAD

**Issue by suyashbakshi** [ZigZag-Project/zigzag-v1#16]
Hello,
I am a little confused about how the total memory consumed for an operand at a memory level is computed. Let me show by an example:
I defined an architecture which has the "spad_48byte" memory as the register for "output" operand. And then 2 more memory levels above that.
And for a conv layer, the mapping for "output" operand that I got is following:
```
spatial =  [(2, 5), (6, 3), (5, 2), (5, 2), (5, 2), (5, 2)] = [(2, 5), (6, 3), (5, 16)]
temporal = [(6, 16), (1, 5), (5, 2)], [(4, 13)], [(3, 13), (5, 6), (6, 4)]   #3 memory levels (RF, local shared buffer, DRAM)
```

My understanding for the example in your paper is that the total memory required for an operand at any memory level is the product of spatial and temporal relevant loops up till that memory level. So in that case, the total memory required for output at the register level by all the PEs will be 
```
= (6, 3)_spatial x (6, 16)_RF_temporal = 48 elements of 2 bytes each = 96 bytes
```
However, the architecture only has 48 bytes at register level. So how is this a valid mapping?

My guess is that it has something to do with "memory_unroll" parameter, but I cannot understand this fully. 

I'd greatly appreciate your help with this. Thank you
-- Suyash

**Comment by LY-Mei** [comment]
Hi Suyash,

If you define the spatial mapping loops at the RF level, it means that your RF will be unrolled multiple times and the total memory capacity at that level will be the defined RF capacity times the total unrolled factor. Yes, "memory_unroll" captures this attribute.

Best regards,
Linyan

**Comment by suyashbakshi** [comment]
Thanks Linyan. That makes sense.

**Comment by asyms** [comment]
To clarify a bit more:

You can thus obtain the number of elements stored for an operand in a level by multiplying all temporal loops up until that level with all spatial loops up until one level lower.
