### ISSUE TITLE
error for matrix 7x7 multiply

### ISSUE THREAD

**Issue by cstutor888** [ZigZag-Project/zigzag-v1#17]
I tried two matrix 7x7 multiply, PE_array 8x8, I've got the following message:
layer_n: 2 {'B': 7, 'K': 7, 'C': 7, 'OY': 1, 'OX': 1, 'FY': 1, 'FX': 1, 'SY': 1, 'SX': 1, 'SFY': 1, 'SFX': 1, 'PY': 0, 'PX': 0, 'G': 1}
ZigZag started running.
Target workload: AlexNet | Layer(s): [2]
MEM HIERARCHY  1 / 1
memory size: {'W': [3584, 10000000000], 'I': [192, 884736, 10000000000], 'O': [384, 884736, 10000000000]}
memory unroll: {'W': [64, 1], 'I': [64, 1, 1], 'O': [64, 1, 1]}
memory share: {0: [('W', 1), ('I', 2), ('O', 2)], 1: [('I', 1), ('O', 1)]}
11:59:20 AlexNet L 2 , M 1 / 1  SUG started
Process Process-2:1:
Traceback (most recent call last):
  File "/home/jon/Projects/zigzag-ug/msg.py", line 1186, in spatial_unrolling_generator_even
    return spatial_loop_list, flooring_list, mem_scheme, not_good
UnboundLocalError: local variable 'not_good' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jon/anaconda3/envs/py36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jon/anaconda3/envs/py36/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jon/Projects/zigzag-ug/evaluate.py", line 768, in mem_scheme_evaluate
    input_settings.spatial_unrolling_mode)
  File "/home/jon/Projects/zigzag-ug/msg.py", line 1189, in spatial_unrolling_generator_even
    'No spatial unrolling found. Consider lowering down the spatial_utilization_threshold in setting file.')
ValueError: No spatial unrolling found. Consider lowering down the spatial_utilization_threshold in setting file.
Traceback (most recent call last):
  File "slam_top_module.py", line 234, in <module>
    of.print_helper(input_settings, layers, layers_saved, multi_manager)
  File "/home/jon/Projects/zigzag-ug/output_funcs.py", line 1756, in print_helper
    parent_str = 'L_%d' % layers[j].parent
TypeError: %d format: a number is required, not NoneType

**Comment by LY-Mei** [comment]
Hi cstutor888,

Could you attach all your setting files and the workload file? So that I can reproduce the error you got and check where could the issue be.

Best regards,
Linyan

**Comment by LY-Mei** [comment]
Hi cstutor888,

I received your files and had a look. The issue you had is due to that the spatial mapping search engine cannot find a valid design point with the utilization threshold you set. What you need to do is change 2 things in the settings.yaml: (1) reduce the spatial_utilization_threshold from the original 0.9 to a lower value, like 0.5; (2) change the spatial_unrolling_search_method to greedy_mapping_without_hint, which allows mapping any spatial loop size to any array size (e.g., map loop size 7 of an array size of 8 in your case).

Best regards,
Linyan
