### ISSUE TITLE
Matrix multiplication operate multiple times

### ISSUE THREAD

**Issue by cstutor888** [ZigZag-Project/zigzag-v1#18]
how can I set up the workload file, if I want two matrix multiplication (4x4)x(4x4), repeat 100 times? what are the B, K, C, or any other parameters?

**Comment by LY-Mei** [comment]
Hi cstutor888, you can set B=4, K=4, C=4, G=100.

**Comment by LY-Mei** [comment]
G is a parameter that we used to model Group Convolution.
