### ISSUE TITLE
Incorrect output reuse

### ISSUE THREAD

**Issue by suyashbakshi** [ZigZag-Project/zigzag-v1#20]
Hello, for a architecture with 3-levels of memory (L0, L1, L2) and 16x16 PE array, following is one of the mappings that I got.
```
{'W': [[(4, 13), (6, 2), (6, 2), (6, 2), (6, 2)], [(6, 12), (2, 5), (3, 13), (5, 3)], [(1, 5)], [(5, 64)]], 'I': [[(4, 13), (6, 2), (6, 2), (6, 2), (6, 2)], [(6, 12), (2, 5), (3, 13), (5, 3)], [(1, 5)], [(5, 64)]], 'O': [[(4, 13), (6, 2), (6, 2), (6, 2), (6, 2)], [(6, 12), (2, 5), (3, 13), (5, 3)], [(1, 5)], [(5, 64)]]}
```
The mapping has levels: [spatial, L0, L1, L2]

The statistics reported shows that the reuse of "output" operand at L0 is 4800. To me that does not seem quite right. Could you please help me out?

**Comment by LY-Mei** [comment]
Sure. Could you upload or email me (linyan.mei@kuleuven.be) the corresponding output report file (the .xml file)?
