### ISSUE TITLE
Some Issues with estimation cost run

### ISSUE THREAD

**Issue by Osogire** [ZigZag-Project/zigzag-v1#6]
Hi,

I'm using ZigZag for a master project and it seems like I found some issues while trying running the framework.

My Goal is to execute a cost estimation so I changed the settings as it was written in the Readme in " inputs/settings.yaml " :
![sets1](https://user-images.githubusercontent.com/39104519/111493661-11208c80-873e-11eb-8a8e-80cb32bc948f.png)

I got a this error :
```
Traceback (most recent call last):
  File "/home/paul/anaconda3/envs/py37/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/paul/anaconda3/envs/py37/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/paul/Documents/M1/projetS2/zigzag/evaluate.py", line 525, in mem_scheme_su_evaluate
    if tl_list and not discard_mem_scheme:
UnboundLocalError: local variable 'tl_list' referenced before assignment
```
I was thinking it may be because the variables are not well set in "evaluate.py" but I really don't know actually.

Then I changed the temporal mapping search method from "loma" to "exhaustive" and got another error which is very strange because I'm running the cost evaluator and not the temporal mapping optimization :
```Traceback (most recent call last):
  File "/home/paul/anaconda3/envs/py37/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/paul/anaconda3/envs/py37/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/paul/Documents/M1/projetS2/zigzag/evaluate.py", line 319, in mem_scheme_su_evaluate
    results = pool.starmap(tl_worker, [[tl_chunk] + fixed_args for tl_chunk in tl_list])
  File "/home/paul/anaconda3/envs/py37/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/paul/anaconda3/envs/py37/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ValueError: For operand W, your mapping size (663552) does not match with the NN layer size (442368). Please check your mapping setting.
```
Then I wanted to try a temporal mapping exploration with "exhaustive" and "loma" method and it seemed to work well.

Finally I found out that doing twice the same run (with same settings) returns the following error :
```
Traceback (most recent call last):
  File "top_module.py", line 168, in <module>
    of.print_helper(input_settings, layers, layers_saved, multi_manager)
  File "/home/paul/Documents/M1/projetS2/zigzag/output_funcs.py", line 1756, in print_helper
    parent_str = 'L_%d' % layers[j].parent
TypeError: %d format: a number is required, not NoneType
```

I don't know wether this issue really need an explanation because the quick fix is to change the result folder (or file name) in the settings or delete it before running again but I feel a bit stucked with the other issues. 

Best regards,
Paul Delarue

**Comment by asyms** [comment]
Hi Paul,
Thanks for sharing your issues.

Issue 1
I have pushed an update to the code fixing this. You are right to say that the Cost model evaluation shouldn't depend on the temporal search method set. Now you should get the "mapping size does not match with NN layer size" error when using loma aswell.

Issue 2
I suspect that the mapping you specified in "inputs/mapping.yaml" does not match with the layer. Could you share with me the layer specification you are trying to run, and the mapping (spatial+temporal) you specified?
If you do a temporal mapping exploration, ZigZag will always generate valid mappings, so then the issue would naturally disappear.

Issue 3
You can avoid this error by commenting L624-628 in evaluate.py
These lines check if the output files already exist and return if this is the case.

Kind regards,
Arne

**Comment by Victor-Jung** [comment]
Hi Arne,

Paul is working with me on the Reinforcement Learning for temporal mapping optimization, and he's not available today.

Thanks for the fix on the Issue 1 and the advice on Issue 3, about the Issue 2 we used the default "mapping.yaml" and "architecture.yaml" for a **single cost estimation** as specified in the "Examples" section of the README.  

I attached here the [default_inputs.zip](https://github.com/ZigZag-Project/zigzag/files/6163385/default_inputs.zip) we have.

BR,

Victor Jung

**Comment by asyms** [comment]
Hi Victor,

The default mapping.yaml won't work for multiple layers that have different dimensions.
If you want to specify the mapping yourself, you have to make sure that:
1.) The product of all dimensions defined in "mapping.yaml" matches the total dimension of that loop type
2.) The memories to which you assign the temporal loops must be large enough to hold those loops

If you let ZigZag do a temporal search, you can see in the generated output file the structure of the temporal mapping it found.
I hope this explanation clears up some confusion, we could also have a call if you want to discuss in more detail.

**Comment by asyms** [comment]
Closing as this issue is resolved.
